### ISSUE TITLE
How to use this? 

### ISSUE THREAD

**Issue by kshalini** [alrojo/lasagne_residual_network#2]
@alrojo  
this seems quite exciting and interesting to try out. but how to use this? just install Lasagne (dependencies) and run the Python code here? 

also which training data to use and where to place that? 

will mostly try this out on a AWS GPU running 14.04 Ubuntu. 

if you please point out to any key steps it would be really wonderful. thanks!

**Comment by alrojo** [comment]
@kshalini 

I figure you might not be the only one, so I have updated the README.md in the main folder with specifics on installation and setup.

If any of it guidelines does not work for you, please let me know and I will look into it :)

**Comment by kshalini** [comment]
thats actually awesome @alrojo ! greatly appreciate your quick turn around. will give this a try and get back if I run into any further issues. thanks!

**Comment by alrojo** [comment]
No problem, I will close this issue then. If you run into further problems, don't hesitate to create a new issue!
