### ISSUE TITLE
module object has no attribute  'Expressionlayer'

### ISSUE THREAD

**Issue by styleNie** [alrojo/lasagne_residual_network#3]
I just run the demo according to the README.md and got a error: 
Amount of bottlenecks: 8
Loading data...
Building model and compiling functions...
Traceback (most recent call last):
  File "Deep_Residual_Network_mnist.py", line 493, in <module>
    main(**kwargs)
  File "Deep_Residual_Network_mnist.py", line 336, in main
    network = build_cnn(input_var, n, num_filters)
  File "Deep_Residual_Network_mnist.py", line 96, in build_cnn
    expression = lasagne.layers.ExpressionLayer
AttributeError: 'module' object has no attribute 'ExpressionLayer'

**Comment by alrojo** [comment]
Thanks for bug report!

Apparently ExpressionLayer was added very recently (15'th November 2015). Here is the commit: https://github.com/Lasagne/Lasagne/commit/ce4f1d80d3c8cf917320f7aaa5ef9bb635b738df

As I assume this is not available unless you have the bleeding edge version, I have updated the code (you will need to git pull in your repo for the updates) to use the `projection_b` that projects with convolutions instead.

If you want to use `projection_a` you will need to update your lasagne (probably to the bleeding edge version) and change `projection_type = 'B'` to `projection_type = 'A'`.

If you still have issues, please let me know.

**Comment by styleNie** [comment]
Thanks for you help!
According to your description, I have updated the Lasagne, but there were some new problems
C:\Users\Administrator\Desktop\lasagne_residual_network-master>python Deep_Resid
ual_Network_mnist.py 8 3 500
Using gpu device 0: GeForce GT 630 (CNMeM is enabled with initial size: 75.0% of
 memory, CuDNN not available)
Amount of bottlenecks: 8
Loading data...
Building model and compiling functions...
Traceback (most recent call last):
  File "Deep_Residual_Network_mnist.py", line 486, in <module>
    main(*_kwargs)
  File "Deep_Residual_Network_mnist.py", line 329, in main
    network = build_cnn(input_var, n, num_filters)
  File "Deep_Residual_Network_mnist.py", line 270, in build_cnn
    l1_bs = blockstack(l1, n=n)
  File "Deep_Residual_Network_mnist.py", line 257, in blockstack
    l = res_block(l, nonlinearity=nonlin)
  File "Deep_Residual_Network_mnist.py", line 231, in bottleneck_block_fast
    W=lasagne.init.HeNormal(gain='relu'))
  File "D:\soft\python\lib\site-packages\lasagne-0.2.dev1-py2.7.egg\lasagne\laye
rs\conv.py", line 526, in **init**
    *_kwargs)
  File "D:\soft\python\lib\site-packages\lasagne-0.2.dev1-py2.7.egg\lasagne\laye
rs\conv.py", line 225, in **init**
    self.W = self.add_param(W, self.get_W_shape(), name="W")
  File "D:\soft\python\lib\site-packages\lasagne-0.2.dev1-py2.7.egg\lasagne\laye
rs\base.py", line 214, in add_param
    param = utils.create_param(spec, shape, name)
  File "D:\soft\python\lib\site-packages\lasagne-0.2.dev1-py2.7.egg\lasagne\util
s.py", line 330, in create_param
    "Tried to create param with shape=%r, name=%r") % (shape, name))
ValueError: Cannot create param with a non-positive shape dimension. Tried to cr
eate param with shape=(0, 3, 1, 1), name='W'

**Comment by alrojo** [comment]
Hi,
Sorry for the delayed answer!
It seems like I have reversed the order of the arguments to the sysargs (num_blocks and num_filters). I have updated the README.md with the correct ones.
Try with this instead:

> > python Deep_Residual_Network_mnist.py 3 8 500

Further, I have updated the code to have CuDNN being disabled by default. To get this you will need to `git pull` to get the latest version.
If you want to enable CuDNN (given it is installed on your system) I have supplied a guide enabling CuDNN in the README.md.

If you still have issues, please let me know.
